version: '3'
services:
  patrns:
    image: kfirbreger/patrns
    expose:
      - "80"

  kfirbreger:
    image: kfirbreger/kfirbreger.com
    expose:
      - "80"

  bunnyapprovesthesechanges:
    image: kfirbreger/bunnyapprovesthesechanges
    expose:
      - "8000"

  nginx:
    image: kfirbreger/conopa-reverseproxy
    ports:
      - "80:80"
      - "433:433"
